# Generated by Django 3.2.16 on 2023-03-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_auto_20230319_1522"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="title",
            field=models.CharField(default="123", max_length=64),
        ),
    ]
