# Generated by Django 3.2.16 on 2023-03-20 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0004_auto_20230319_1722"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="follow",
            constraint=models.UniqueConstraint(
                fields=("user", "following"), name="unique_user_following"
            ),
        ),
    ]
